### ISSUE TITLE
Rewrite rules for files under the public folder.

### ISSUE THREAD

**Issue by 8masterofpuppets8** [GraffiTab/GraffiTab-Backend#102]
Some system require files to be accessed from the root website folder such as robots.txt and apple-app-site-association.

We should provide rewrite tules for those files from HAProxy so that they can be read publicly.

https://www.haproxy.com/doc/aloha/7.0/haproxy/http_rewriting.html

**Comment by dfernandezm** [comment]
The configuration needed was added here:

https://github.com/GraffiTab/GraffiTab-Backend/commit/0efa8600007ddd699fdb36fa6ad8b8ca7dd00fb0
