### ISSUE TITLE
Install HTTPS intermediate certificates

### ISSUE THREAD

**Issue by 8masterofpuppets8** [GraffiTab/GraffiTab-Backend#110]
http://serverfault.com/questions/623068/haproxy-and-intermediate-ssl-certificate-issue

**Comment by dfernandezm** [comment]
The PEM file is missing the bundle with the intermediate certificates. This is failing to validate in Firefox and Chrome on Android.

This is a useful link on how to properly generate the PEM file:
https://lucianpantelimon.info/setting-up-haproxy-with-comodo-positivessl-certificates/

Update the docs around `load-balancer` section with the following:

```
mkdir /tmp/certificate
cd /tmp/certificate
touch graffitab.com.pem
unzip graffitab_com.zip

# This order matters
cat graffitab.com.key >> graffitab.com.pem
cat graffitab_com.crt >> graffitab.com.pem
cat graffitab_com.ca-bundle >> graffitab.com.pem
cp graffitab.com.pem /etc/ssl/private

# Restart LB
service haproxy restart
```

**Comment by dfernandezm** [comment]
Created separate issue for this  #111
