### ISSUE TITLE
Reconfigure app user and SSHFS on DEV and PROD

### ISSUE THREAD

**Issue by 8masterofpuppets8** [GraffiTab/GraffiTab-Backend#117]

**Comment by dfernandezm** [comment]
Updated docs with commands to persist SSHFS. For now it is not persistent on restarts.

**Comment by dfernandezm** [comment]
Fixed the permission directly on the server. `graffitab` user is used everywhere

**Comment by dfernandezm** [comment]
This is going to be ditched as now asset resizing runs on each individual server, so no need for SSHFS
