### ISSUE TITLE
Registration broken - No message found under code 'email.subject.welcome' for locale 'en'.

### ISSUE THREAD

**Issue by 8masterofpuppets8** [GraffiTab/GraffiTab-Backend#131]
User registration appears to be broken. Looking at the server log, we have an exception. More details:

**What was the intended action?**

Register new user.

**What is the expected result?**

Registration is successful and new user gets welcome email.

**What actually happened?**

Got an error on the client side.

**Logs**

```
2017-05-27 06:23:13,684 [http-nio-8091-exec-8] [] ERROR GeneralErrorHandlingAdvice.generalException - Error occurred processing request
org.springframework.context.NoSuchMessageException: No message found under code 'email.subject.welcome' for locale 'en'.
	at org.springframework.context.support.DelegatingMessageSource.getMessage(DelegatingMessageSource.java:69) ~[spring-context-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at com.graffitab.server.service.email.EmailService.sendWelcomeEmail(EmailService.java:32) ~[classes!/:?]
	at com.graffitab.server.service.user.UserService.createUser(UserService.java:241) ~[classes!/:?]
```

**Comments**

Looks like the key `email.subject.welcome` cannot be found in the message.properties. I looked at the files on the server and it seems to be there. It could be related to the Spring Boot upgrade. Not critical at the moment but when we send it to people they should be able to register properly.

**Comment by dfernandezm** [comment]
Fixing createUserTest by mocking this messageSource hid this issue, the test was actually being really helpful to show the issue.

More info: the upgrade to v1.4.0 (not only 1.5.1) might have introduced issues with default locales (en_US) and default message files (which is now `messages.properties`, which we don't have, as we have different languages). 

https://github.com/spring-projects/spring-boot/issues/4930

Possible solutions to test:
* Add message.properties to the JAR and test solution
* Add a localeResolver that defaults to English, without country definition

**Comment by dfernandezm** [comment]
Tested adding message.properties (no language) and registration worked fine. The lack of `Accept-Language` header + the defaulting to `en_US` (due to upgrade?) broke the message detection.

Solutions:

* Always leave messages.properties around (no lang, as it will be fallback)
* But also, ensure that the fallback Locale is always `en` / `en-GB` / `en_GB`
