### ISSUE TITLE
Build 'Who to follow' endpoint 

### ISSUE THREAD

**Issue by dfernandezm** [GraffiTab/GraffiTab-Backend#160]
- [x] Add field to user in database `is_recommended`
- [x] Add migrations for the previous field and for any user created for integrations (DeviantArt, Flickr...)
- [x] Endpoint that returns users with `is_recommended` not followed by current user: `/api/users/me/whotofollow`

**Comment by 8masterofpuppets8** [comment]
Tested this on dev, seems like it works nicely!
