### ISSUE TITLE
Append .jpg to uploaded assets in S3

### ISSUE THREAD

**Issue by 8masterofpuppets8** [GraffiTab/GraffiTab-Backend#172]
Currently when images are uploaded their name is an asset GUID which works fine but when users Share the artwork, browsers start downloading the file rather than display it directly in the webpage. This is an issue because there's no way to edit the file extension from the phones to make the file view-able.

On the other hand, our Bots import content with .jpg appended to the links to the files which makes them viewable directly from the source in the browser.

The suggested way to handle this is to add the .jpg extension to the file names in S3 so that the link to the file is `http://graffitab-store-eu1.s3.amazonaws.com/assets/UzPPIgIValU2v.jpg` rather than `http://graffitab-store-eu1.s3.amazonaws.com/assets/UzPPIgIValU2v`. This will force the browser to load the image directly. 

This is an okay solution until we have post pages on the server.

**Note:** Existing links should remain unchanged. This should only apply to new links.

**Comment by dfernandezm** [comment]
Instead of changing suffix, MediaType was applied to S3 objects
