### ISSUE TITLE
Change password should log out of all sessions apart from the current one

### ISSUE THREAD

**Issue by 8masterofpuppets8** [GraffiTab/GraffiTab-Backend#18]
When a user changes their password, the backend should log them out of all other sessions. However, it should keep or recreate the current one with the new password, so that they don't have to log in again.

**Comment by dfernandezm** [comment]
Yes, I am seeing it a bit clearer. The user can be replaced in the current session with the right password and invalidate the rest. Still think the best would be force a session invalidation, but maybe the previous approach is enough for now.
