### ISSUE TITLE
Research how to add versioning to the API

### ISSUE THREAD

**Issue by dfernandezm** [GraffiTab/GraffiTab-Backend#191]

**Comment by 8masterofpuppets8** [comment]
https://stackoverflow.com/questions/20198275/how-to-manage-rest-api-versioning-with-spring

One of the solutions here is very interesting and elegant, using annotations and possible versions with automatic mapping to the correct version url.

**Comment by 8masterofpuppets8** [comment]
Api version is now implemented using a URL-based scheme. The current api is `/v1`. New versions will use their own controllers with appropriate `/v` mappings to override/add endpoints.
