### ISSUE TITLE
Image uploading and resizing

### ISSUE THREAD

**Issue by 8masterofpuppets8** [GraffiTab/GraffiTab-Backend#23]
We would like to resize all uploaded images to make sure they do not exceed certain size and capacity limits. Currently we support 3 image groups - avatars, covers and graffiti. Each image group should have a `maximim` size, i.e. `maxWidth` and `maxHeight`, as well as max size in bytes.

For the following logic, we assume there is a way to get the dimensions of the uploaded file in the server.

**Resizing logic**

When an image upload request is made to either `/avatar`, `/cover` or `/graffiti` and the content length checks and file type checks pass, we obtain the `width` and `height` of the image. Depending what image group the image is in, we check it's dimensions against the maximum for that image group. For example if the maximum graffiti size is 1024x768 and the uploaded image has size 800x600, it will not get resized, because it is already contained within the maximum allowed size for that image group. However, if the uploaded image has size 1000x900, it should get scaled down to WIDTHx768, where WIDTH is the aspect-correct width for the image after scaling it down to fit the height.

Similarly, if the uploaded image has size 2000x600, it should be scaled down to fit the maximum width.

Finally, if the uploaded image has size 2000x1200, it should be scaled down to fit both the max width and max height.

**Comment by dfernandezm** [comment]
@8masterofpuppets8 ready to merge into master right?

**Comment by 8masterofpuppets8** [comment]
Yep, looks ready to me. Go go go
