### ISSUE TITLE
Allow login using email

### ISSUE THREAD

**Issue by dfernandezm** [GraffiTab/GraffiTab-Backend#43]
The backend should support logging in using the email as well as the username.

**Comment by 8masterofpuppets8** [comment]
Login works but no session is stored in the database which prevents any further calls and throws a 401 error. Tried with the following curl command:

```
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{
    "username":"georgi", 
    "password":"password1"
}' "http://localhost:8091/api/login"
```

The result is correct but no session is created in the database.
